### ISSUE TITLE
how to fix the error:"Unsupported major.minor version 52.0"?

### ISSUE THREAD

**Issue by luckypoem** [outloudvi/gogo-server#1]
hi.

root@ar:~# java -jar gogo-server-1.8.0.jar 8080
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/gogo/GoGoServer : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
root@ar:~#

**Comment by outloudvi** [comment]
It seems to be a problem of Gogotunnel itself, rather than the Dockerfile. Maybe you can get help from the developers of that.

Feel free to reopen it and tell me if you are experiencing problems with the Dockerfile but working on your own pc.
